#!/usr/bin/env python3
"""Explicitly serialize shipped cognitive projects into a fresh fixture copy.

Refuses to overwrite fixtures. Expected cognitive task results are constants in
cognitive_model_regressions.py and are never generated by this migration.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil

from modern_stack_regressions import Case, REPO, require, runtime_diagnostics

MODELS = {
    'count': ('Count', 'CountModel', 'ActrCount.proj'),
    'semantic': ('ActRTest', 'semantic', 'ActrSemantic.proj'),
}
SNAPSHOT = '''
for(int ci=0;ci<cognitive_model->chunk_types.size;ci++) cout << "COGNITIVE_TYPE " << cognitive_model->chunk_types[ci].name << endl;
ActrProceduralModule* cognitive_proc = cognitive_model->ProceduralModule();
for(int ci=0;ci<cognitive_proc->productions.size;ci++) cout << "COGNITIVE_PRODUCTION " << cognitive_proc->productions[ci].name << " " << cognitive_proc->productions[ci].conds.size << " " << cognitive_proc->productions[ci].acts.size << endl;
ActrDeclarativeModule* cognitive_dm = cognitive_model->DeclarativeModule();
for(int ci=0;ci<cognitive_dm->init_chunks.size;ci++) {
 ActrChunk* cognitive_chunk = cognitive_dm->init_chunks[ci];
 cout << "COGNITIVE_MEMORY " << cognitive_chunk->name;
 for(int si=0;si<cognitive_chunk->slots.size;si++) cout << " | " << cognitive_chunk->slots[si].name << "=" << cognitive_chunk->slots[si].val;
 cout << endl;
}
ActrGoalModule* cognitive_goal = cognitive_model->GoalModule();
for(int ci=0;ci<cognitive_goal->init_chunk.size;ci++) {
 ActrChunk* cognitive_chunk = cognitive_goal->init_chunk[ci];
 cout << "COGNITIVE_GOAL " << cognitive_chunk->name;
 for(int si=0;si<cognitive_chunk->slots.size;si++) cout << " | " << cognitive_chunk->slots[si].name << "=" << cognitive_chunk->slots[si].val;
 cout << endl;
}
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--model', action='append', choices=MODELS)
    parser.add_argument('--binary', type=Path, default=REPO / 'tools/run-emergent')
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--destination', type=Path, default=REPO / 'test/fixtures/modern')
    parser.add_argument('--timeout', type=float, default=90)
    args = parser.parse_args()
    args.binary = args.binary.resolve(); args.output = args.output.resolve()
    args.destination = args.destination.resolve()
    args.output.mkdir(parents=True, exist_ok=False)
    args.destination.mkdir(parents=True, exist_ok=True)
    metadata = args.destination / 'cognitive-provenance.json'
    previous = json.loads(metadata.read_text()) if metadata.exists() else {'fixtures': []}
    records = previous['fixtures'] if 'fixtures' in previous else [previous]
    for name in args.model or MODELS:
        program, model, filename = MODELS[name]
        source = REPO / 'demo/actr' / (name + '.proj')
        destination = args.destination / filename
        require(not destination.exists(), f'refusing to overwrite {destination}')
        case = Case(args, name + '-legacy', allow_diagnostics=True)
        case.fixture = case.directory / source.name
        shutil.copy2(source, case.fixture)
        prefix = f'ActrModel* cognitive_model = .projects[0].programs["{program}"].objs["{model}"];\n'
        # Semantic's old vision reference is restored by the normal module Init
        # path. Count requires serialization migration only.
        initialize = 'cognitive_model->Init();\n' if name == 'semantic' else ''
        case.css(prefix + initialize + SNAPSHOT + f'\n.projects[0].SaveCopy("{destination}");\n'
                 'cout << "MODERN_PASS saved" << endl;\ncout << "MODERN_COMPLETE" << endl;\n', ['saved'], name='migrate')
        before_text = (case.directory / 'migrate.log').read_text()
        diagnostics = runtime_diagnostics(before_text)
        require(len(diagnostics) == 2 and all('SAVE_ROWS' in d or 'Regents of the University of Colorado' in d for d in diagnostics),
                f'unexpected legacy diagnostics: {diagnostics}')
        migrated = Case(args, name + '-modern'); migrated.fixture = destination
        migrated.css(prefix + initialize + SNAPSHOT + '\ncout << "MODERN_PASS reloaded" << endl;\ncout << "MODERN_COMPLETE" << endl;\n',
                     ['reloaded'], name='reload')
        signature = lambda text: [line for line in text.splitlines() if line.startswith('COGNITIVE_')]
        before = signature(before_text); after = signature((migrated.directory / 'reload.log').read_text())
        require(before == after, 'model types/productions/memory/goal changed during migration')
        record = {'source': str(source.relative_to(REPO)), 'source_sha256': hashlib.sha256(source.read_bytes()).hexdigest(),
                  'destination': str(destination.relative_to(REPO)) if destination.is_relative_to(REPO) else str(destination),
                  'destination_sha256': hashlib.sha256(destination.read_bytes()).hexdigest(),
                  'method': 'Real Emergent Load, ' + ('normal model Init, ' if initialize else '') + 'SaveCopy and fresh process reload; no model/production/parameter edits.',
                  'legacy_status': 'STALE_SERIALIZATION', 'legacy_diagnostics': diagnostics,
                  'preserved_model_signature': before, 'evidence': str(args.output),
                  'expected_results': 'Fixed assertions in cognitive_model_regressions.py; no generated baseline.'}
        records.append(record)
        metadata.write_text(json.dumps({'fixtures': records}, indent=2) + '\n')
        print('Migrated', name, destination, flush=True)


if __name__ == '__main__':
    main()
